### ISSUE TITLE
find in files

### ISSUE THREAD

**Issue by amitkle** [jupyterlab-contrib/jupyterlab-quickopen#12]
Hey,
Do you perhaps work on a find in files feature inside your search?
If not, I was thinking to add this by myself.
what do you think?
Also, is there a chance that the extension doesn't work on jupyerlab2?
thanks!

**Comment by parente** [comment]
Hi @amitkle. There's a discussion in #11 about 2.x support.

I think search within files is a fantastic idea for a separate extension, just as it's a separate feature from quick open in most text editors. There's a classic notebook extension that had a really rudimentary implementation over in https://github.com/jupyter-incubator/contentmanagement#what-it-gives-you.

**Comment by amitkle** [comment]
I was thinking suits here because I imagined something like windows explorer search:
The first results are the files that their names match, and then the next results are from inside the files.

The link you sent me is really cool! its a shame that it works only in classic notebook...

**Comment by jtpio** [comment]
@amitkle there is now a `search-replace` extension for JupyterLab, which can found here: https://github.com/jupyterlab-contrib/search-replace

And it can be installed with `pip install jupyterlab-search-replace`.

Feel free to open an issue on that repo if you have any issue or feature request. Thanks!
