### ISSUE TITLE
 Main step in the tutorial notebook fails in MyBinder-served sessions at this time

### ISSUE THREAD

**Issue by fomightez** [jupyterlab-contrib/jupyterlab-quickopen#58]
## Description

 `/usr/share/dict/` is empty in launched MyBinder-served sessions, and so that notebook fails to generate to generate a thousand more files in the notebook tree.

## Reproduce

1. Go to https://github.com/jupyterlab-contrib/jupyterlab-quickopen
2. Click on '`launch binder` badge
3. Run cell that is about generating to generate a thousand more files in the notebook tree. (It is currently the first one.)
4. See error `FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dict/words`.

## Expected behavior

Tutorial steps would not produce errors for users to debug.

## Context

<details><summary>Full Traceback Output</summary>
<pre>
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In[1], line 5
      2 import random
      4 # Get a thousand words
----> 5 with open('/usr/share/dict/words') as fh:
      6     words = fh.readlines()
      7 words = random.choices([w.strip() for w in words if "'" not in w], k=1000)

File `/srv/conda/envs/notebook/lib/python3.10/site-packages/IPython/core/interactiveshell.py:324`, in _modified_open(file, *args, **kwargs)
    317 if file in {0, 1, 2}:
    318     raise ValueError(
    319         f"IPython won't let you open fd={file} by default "
    320         "as it is likely to crash IPython. If you know what you are doing, "
    321         "you can use builtins' open."
    322     )
--> 324 return io_open(file, *args, **kwargs)

FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/dict/words`
</pre>
</details>

## Suggested, validated solution

This can be fixed by adding the following content to a file named `apt.txt` in the `binder` sub-directory:

```shell
wamerican
```

Validated as fixing via testing this in [my fork here](https://github.com/fomigthez/jupyterlab-quickopen). Launch directly [sessions generated from my fork here](https://mybinder.org/v2/gh/fomightez/jupyterlab-quickopen/main?urlpath=lab%2Ftree%2Fbinder%2Ftutorial.ipynb).  
The added `apt.txt` file is [here](https://github.com/fomightez/jupyterlab-quickopen/blob/main/binder/apt.txt) in the `binder` sub-directory of my fork.

**Comment by jtpio** [comment]
Thanks @fomightez for the report!

> Validated as fixing via testing this in [my fork here](https://github.com/fomigthez/jupyterlab-quickopen). Launch directly [sessions generated from my fork here](https://mybinder.org/v2/gh/fomightez/jupyterlab-quickopen/main?urlpath=lab%2Ftree%2Fbinder%2Ftutorial.ipynb).

Would you like to open a PR to add that package to `apt.txt`? Thanks!

**Comment by fomightez** [comment]
Since my form had other changes for testing, I made a branch and reset it back to the source of the fork and only added the apt.txt to that branch. Then made a pull request with that branch. Hopefully, that's all good.
