### ISSUE TITLE
TypeError: object bool can't be used in 'await' expression

### ISSUE THREAD

**Issue by yjoer** [jupyterlab-contrib/jupyterlab-quickopen#61]
## Description

I am using JupyterLab v4.2.5 and v2.0.0 of the extension. It turns out that `is_hidden(...)` returned a boolean instead of an awaitable object. I found that Jupyter Server instantiated a synchronous [contents manager](https://jupyter-server.readthedocs.io/en/latest/api/jupyter_server.services.contents.html#jupyter_server.services.contents.manager.ContentsManager) instead of an async alternative. I removed the `await` keyword in [L42](https://github.com/jupyterlab-contrib/jupyterlab-quickopen/blob/v2.0.0/jupyterlab_quickopen/handler.py#L42) and the opener starts working correctly. A safer solution might be using `ensure_async(...)` as in the [upstream handlers](https://github.com/jupyter-server/jupyter_server/blob/v2.14.2/jupyter_server/base/handlers.py#L1121).

## Reproduce

1. Activate the quick open dialog.
2. Type anything.
3. Find the error message in the terminal.

## Expected behavior

It should return a list of files without errors.

## Context

- Python package version: 3.11.9
- Extension version: v2.0.0
- Operating System and its version: Ubuntu 22.04.5 LTS
- Browser and its version: Chrome 129

<details><summary>Command Line Output</summary></details>

```diff
[W 2024-10-03 22:36:10.945 ServerApp] wrote error: 'Unhandled error'
    Traceback (most recent call last):
      File "/home/ubuntu/camp/.venv/lib/python3.11/site-packages/tornado/web.py", line 1790, in _execute
        result = await result
                 ^^^^^^^^^^^^
      File "/home/ubuntu/camp/.venv/lib/python3.11/site-packages/jupyterlab_quickopen/handler.py", line 83, in get
        contents_by_path = await self.scan_disk(full_path, excludes)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/home/ubuntu/camp/.venv/lib/python3.11/site-packages/jupyterlab_quickopen/handler.py", line 51, in scan_disk
        if await self.should_hide(entry, excludes):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
+     File "/home/ubuntu/camp/.venv/lib/python3.11/site-packages/jupyterlab_quickopen/handler.py", line 42, in should_hide
+       self.contents_manager.is_hidden(entry.path)
    TypeError: object bool can't be used in 'await' expression
```

**Comment by jtpio** [comment]
Thanks @yjoer for the report.

Would you like to open a draft PR to try fixing this? Thanks!

**Comment by yjoer** [comment]
I created a draft PR in #62 with a more precise finding.
